language: ruby
branches:
  only:
    - master
services:
  - mysql
  - postgresql
  - redis-server
addons:
  postgresql: '9.6'
before_script:
  - mysql -e 'create database delayed_job_test;'
  - mysql --version
  - psql -c 'create database delayed_job_test;' -U postgres
script: bundle exec $COMMAND
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS -Xcli.debug=true --debug"
    - COMMAND=rspec
gemfile: # Supported
  - gemfiles/mysql2/5-1.gemfile
  - gemfiles/mysql2/5-2.gemfile
  - gemfiles/mysql2/6-0.gemfile
  - gemfiles/postgresql/5-1.gemfile
  - gemfiles/postgresql/5-2.gemfile
  - gemfiles/postgresql/6-0.gemfile
  - gemfiles/sqlite3/5-1.gemfile
  - gemfiles/sqlite3/5-2.gemfile
  - gemfiles/sqlite3/6-0.gemfile
rvm: # Supported
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - jruby-9.2.7.0

jdk: oraclejdk11

matrix:
  allow_failures:
    - rvm: jruby-head # Future
    - rvm: rbx-2 # Parallel dimension
    - rvm: ruby-head # Future
    - gemfile: gemfiles/mysql2/master.gemfile # Future
    - gemfile: gemfiles/postgresql/master.gemfile # Future
    - gemfile: gemfiles/sqlite3/master.gemfile # Future

  exclude:
    - gemfile: gemfiles/mysql2/6-0.gemfile
      rvm: 2.3.8
    - gemfile: gemfiles/mysql2/6-0.gemfile
      rvm: 2.4.6
    - gemfile: gemfiles/postgresql/6-0.gemfile
      rvm: 2.3.8
    - gemfile: gemfiles/postgresql/6-0.gemfile
      rvm: 2.4.6
    - gemfile: gemfiles/sqlite3/6-0.gemfile
      rvm: 2.3.8
    - gemfile: gemfiles/sqlite3/6-0.gemfile
      rvm: 2.4.6

  include:
    #
    # Rubocop
    #
    - rvm: 2.5.5
      gemfile: Gemfile
      env:
        - COMMAND=rubocop
    #
    # The future
    #
    # Active Record head
    - rvm: 2.5.5
      gemfile: gemfiles/mysql2/master.gemfile
    - rvm: 2.5.5
      gemfile: gemfiles/postgresql/master.gemfile
    - rvm: 2.5.5
      gemfile: gemfiles/sqlite3/master.gemfile
    - rvm: 2.6.3
      gemfile: gemfiles/mysql2/master.gemfile
    - rvm: 2.6.3
      gemfile: gemfiles/postgresql/master.gemfile
    - rvm: 2.6.3
      gemfile: gemfiles/sqlite3/master.gemfile
    # MRI Ruby head
    - rvm: ruby-head
      gemfile: gemfiles/mysql2/5-2.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/postgresql/5-2.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/sqlite3/5-2.gemfile
    # JRuby head
    - rvm: jruby-head
      gemfile: gemfiles/mysql2/5-2.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/postgresql/5-2.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/sqlite3/5-2.gemfile
    #
    # The past
    #
    # EOL Active Record
    # Rails 5.0 was EOL with the release of 5.2
    - rvm: 2.4.6
      gemfile: gemfiles/mysql2/5-0.gemfile
    - rvm: 2.4.6
      gemfile: gemfiles/postgresql/5-0.gemfile
    - rvm: 2.4.6
      gemfile: gemfiles/sqlite3/5-0.gemfile
    #
    # The parallel dimension
    #
    # Rubinius
    - rvm: rbx-2
      gemfile: gemfiles/mysql2/5-1.gemfile
    - rvm: rbx-2
      gemfile: gemfiles/postgresql/5-1.gemfile
    - rvm: rbx-2
      gemfile: gemfiles/sqlite3/5-1.gemfile

sudo: false
